platform :ios, '9.0'
use_frameworks!

target 'ImageIOSwift_Example' do
  pod 'ImageIOSwift', :path => '../'
  pod 'ImageIOUIKit', :path => '../'

  target 'ImageIOSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
