platform :ios, '9.0'
use_frameworks!

target 'ImageIOSwift_Example' do
  pod 'ImageIOSwift', :path => '../'
  pod 'ImageIOUIKit', :path => '../'

  target 'ImageIOSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

target 'example-swiftui-ios' do
  platform :ios, '13.0'
  
  pod 'ImageIOSwift', :path => '../'
  pod 'ImageIOSwiftUI', :path => '../'
end

target 'example-swiftui-mac' do
  platform :osx, '10.15'
  
  pod 'ImageIOSwift', :path => '../'
  pod 'ImageIOSwiftUI', :path => '../'
end

target 'example-swiftui-watch-extension' do
  platform :watchos, '6.0'
  
  pod 'ImageIOSwift', :path => '../'
  pod 'ImageIOSwiftUI', :path => '../'
end
